version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - ETHEREUM_ADDRESS=${ETHEREUM_ADDRESS}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
